import os

DATA_DIRECTORY = config['DIRECTORIES']['DATA_DIRECTORY']
OUTDIR = config['DIRECTORIES']['OUTPUT_DIR']
PREPROCESS_DIR = config['DIRECTORIES']['PREPROCESS_DIRECTORY']
LOG_DIR = os.path.join(OUTDIR, 'log')

rule all:
    input:
        os.path.join(OUTDIR,'ceftype_{}.cef'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'{}_pre.csv'.format(config['DATA_NAME']))

rule load_Rscript:
    shell: "module load r/4.0.0"

rule preprocess_cef_conv:
    output:
        os.path.join(OUTDIR,'ceftype_{}.cef'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][PREPROCESS_CEF_CONVERT]} ' 
        '--data_output_directory {config[DIRECTORIES][OUTPUT_DIR]} '
        '--console_output_directory {config[LOG][PREPROCESS_LOG]}/cef_conv.out '
        '--input_directory {config[DIRECTORIES][CEF_INPUT]} ' 
        '--name_dataset {config[DATA_NAME]}'
rule preprocess_data:
    output:
        os.path.join(OUTDIR,'{}_pre.csv'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][PREPROCESS_DATA]} ' 
        '--data_output_directory {config[DIRECTORIES][OUTPUT_DIR]} '
        '--console_output_directory {config[LOG][PREPROCESS_LOG]}/cef_conv.out '
        '--input_directory {config[DIRECTORIES][DATA_DIRECTORY]} ' 
        '--name_dataset {config[DATA_NAME]}'



