import os

DATA_DIRECTORY = config['DIRECTORIES']['DATA_DIRECTORY']
OUTDIR = config['DIRECTORIES']['OUTPUT_DIR']
PREPROCESS_DIR = config['DIRECTORIES']['PREPROCESS_DIRECTORY']
LOG_DIR = os.path.join(OUTDIR, 'log')
TRUE_DIR=config['DIRECTORIES']['TRUE_CLUSTER_DIR']
rule all:
    input:
        os.path.join(OUTDIR,'AIR+VM+PURITY','{}.txt'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'cMatrix','{}.txt'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'heatmap','{}.txt'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'tSNE+PCA','{}.txt'.format(config['DATA_NAME']))
rule PURITY:
    output:
        os.path.join(OUTDIR,'AIR+VM+PURITY','{}.txt'.format(config['DATA_NAME']))
    shell:
        'Rscript {config[SOFTWARE][PURITY]} '
        '--output_directory {OUTDIR}/AIR+VM+PURITY ' 
        '--preprocessed_input_directory {PREPROCESS_DIR} '
        '--true_cluster_input_directory {TRUE_DIR} '
        '--sc3_cluster_input_directory {config[DIRECTORIES][SC3_CLUSTER]} '
        '--seurat_cluster_input_directory {config[DIRECTORIES][SEURAT_CLUSTER]} '
        '--giniclust_cluster_input_directory {config[DIRECTORIES][GINICLUST_CLUSTER]} ' 
        '--backspin_cluster_input_directory {config[DIRECTORIES][BACKSPIN_CLUSTER]} ' 
        '--name_dataset {config[DATA_NAME]} '
rule cMATRIX:
    output:
        os.path.join(OUTDIR,'cMatrix','{}.txt'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][cMATRIX]} '
        '--output_directory {OUTDIR}/cMatrix ' 
        '--preprocessed_input_directory {PREPROCESS_DIR} '
        '--true_cluster_input_directory {TRUE_DIR} '
        '--sc3_cluster_input_directory {config[DIRECTORIES][SC3_CLUSTER]} '
        '--seurat_cluster_input_directory {config[DIRECTORIES][SEURAT_CLUSTER]} '
        '--giniclust_cluster_input_directory {config[DIRECTORIES][GINICLUST_CLUSTER]} ' 
        '--backspin_cluster_input_directory {config[DIRECTORIES][BACKSPIN_CLUSTER]} ' 
        '--name_dataset {config[DATA_NAME]} '
rule heatmap:
    output:
        os.path.join(OUTDIR,'heatmap','{}.txt'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][HEATMAP]} '
        '--output_directory {OUTDIR}/heatmap ' 
        '--preprocessed_input_directory {PREPROCESS_DIR} '
        '--true_cluster_input_directory {TRUE_DIR} '
        '--sc3_cluster_input_directory {config[DIRECTORIES][SC3_CLUSTER]} '
        '--seurat_cluster_input_directory {config[DIRECTORIES][SEURAT_CLUSTER]} '
        '--giniclust_cluster_input_directory {config[DIRECTORIES][GINICLUST_CLUSTER]} ' 
        '--backspin_cluster_input_directory {config[DIRECTORIES][BACKSPIN_CLUSTER]} ' 
        '--name_dataset {config[DATA_NAME]} '

rule tSNE:
    output:
        os.path.join(OUTDIR,'tSNE+PCA','{}.txt'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][TSNE+PCA]} '
        '--output_directory {OUTDIR}/tSNE+PCA ' 
        '--preprocessed_input_directory {PREPROCESS_DIR} '
        '--true_cluster_input_directory {TRUE_DIR} '
        '--sc3_cluster_input_directory {config[DIRECTORIES][SC3_CLUSTER]} '
        '--seurat_cluster_input_directory {config[DIRECTORIES][SEURAT_CLUSTER]} '
        '--giniclust_cluster_input_directory {config[DIRECTORIES][GINICLUST_CLUSTER]} ' 
        '--backspin_cluster_input_directory {config[DIRECTORIES][BACKSPIN_CLUSTER]} ' 
        '--name_dataset {config[DATA_NAME]} '
