import os


OUTDIR = config['DIRECTORIES']['OUTPUT_DIR']
PREPROCESS_DIR = config['DIRECTORIES']['PREPROCESS_DIRECTORY']
LOG_DIR = os.path.join(OUTDIR, 'log')
DATA_NAME = config['DATA_NAME']
rule all:
    input:
        os.path.join(OUTDIR,'sc3','sc3_{}.csv'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'seurat','seurat_{}.csv'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'giniclust','giniclust_{}.csv'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'backspin','backspin_{}.cef'.format(config['DATA_NAME'])),
        os.path.join(OUTDIR,'backspin','backspin_{}.csv'.format(config['DATA_NAME']))
rule sc3:
    output:
        os.path.join(OUTDIR,'sc3','sc3_{}.csv'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][sc3]} ' 
        '--data_output_directory {config[DIRECTORIES][OUTPUT_DIR]}/sc3 '
        '--console_output_directory {config[LOG][CLUSTER_LOG]}/sc3.out '
        '--input_directory {config[DIRECTORIES][PREPROCESS_DIRECTORY]} ' 
        '--name_dataset {config[DATA_NAME]} '
rule seurat:
    output:
         os.path.join(OUTDIR,'seurat','seurat_{}.csv'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][seurat]} ' 
        '--data_output_directory {config[DIRECTORIES][OUTPUT_DIR]}/seurat '
        '--console_output_directory {config[LOG][CLUSTER_LOG]}/seurat.out '
        '--input_directory {config[DIRECTORIES][PREPROCESS_DIRECTORY]} ' 
        '--name_dataset {config[DATA_NAME]} '
rule giniclust:
    output:
         os.path.join(OUTDIR,'giniclust','giniclust_{}.csv'.format(config['DATA_NAME']))

    shell:
        'Rscript {config[SOFTWARE][giniclust]} ' 
        '--data_output_directory {config[DIRECTORIES][OUTPUT_DIR]}/giniclust '
        '--console_output_directory {config[LOG][CLUSTER_LOG]}/giniclust.out '
        '--input_directory {config[DIRECTORIES][PREPROCESS_DIRECTORY]} ' 
        '--name_dataset {config[DATA_NAME]} '
        '--input_raw {config[DIRECTORIES][RAW_DIRECTORY]} '
rule spin:
    output:
         os.path.join(OUTDIR,'backspin','backspin_{}.cef'.format(config['DATA_NAME']))
    shell:
        'backspin -i {config[DIRECTORIES][PREPROCESS_DIRECTORY]}/ceftype_{config[DATA_NAME]}.cef '
        '-o {config[DIRECTORIES][OUTPUT_DIR]}/backspin/backspin_{config[DATA_NAME]}.cef ' 
        '-f 500 -v -d 6'
rule spin_convert:
    output:
         os.path.join(OUTDIR,'backspin','backspin_{}.csv'.format(config['DATA_NAME']))
    shell:
        'Rscript {config[SOFTWARE][spin_convert]} ' 
        '--data_output_directory {config[DIRECTORIES][OUTPUT_DIR]}/backspin '
        '--console_output_directory {config[LOG][CLUSTER_LOG]}/spin_conv.out '
        '--input_directory {config[DIRECTORIES][OUTPUT_DIR]}/backspin ' 
        '--name_dataset {config[DATA_NAME]} '

